.

diff --git a/PKGBUILDs/pkgurl/pkgurl b/PKGBUILDs/pkgurl/pkgurl
--- a/PKGBUILDs/pkgurl/pkgurl
+++ b/PKGBUILDs/pkgurl/pkgurl
@@ -1,81 +1,31 @@
 #!/bin/bash
 
+echo2() { echo "$@" >&2; }
 DIE() {
-    local progname="$(basename "$0")"
-    echo "$progname: error: $1" >&2
+    local progname=${0##*/}
+    echo2 "$progname: error: $1"
     exit 1
 }
 
-Options() {
-    local progname="$(/usr/bin/basename "$0")"
-    local opts
-
-    opts="$(/usr/bin/getopt -o=hf: --longoptions help,field: --name "$progname" -- "$@")" || {
-        Options -h
-        return 1
-    }
-
-    eval set -- "$opts"
-
-    while true ; do
-        case "$1" in
-            -f | --field) field="$2"; shift  ;;
-
-            -h | --help)
-                cat <<EOF >&2
-
-$progname - Show the web page mentioned in the 'URL' or 'AUR URL' property of 'yay -Si pkgname'
-
-Usage: $progname [options] pkgname
-Pkgname               Name of the package for which the information will be fetched.
-Options:
-  -f, --field         Field of 'yay -Si pkgname' ('URL', 'AUR URL') page to fetch.
-  -h, --help          This help.
-
-Note: AUR helpers paru and yay are supported.
-
-EOF
-                exit 0
-                ;;
-            
-            --) shift ; break ;;
-        esac
-        shift
-    done
-
-    pkg="$1"
-
-    [ -n "$pkg" ] || DIE "give package name"
-
-    case "$field" in
-        URL | "AUR URL") ;;
-        *) DIE "unsupported field '$field'" ;;
-    esac
-}
-
 Main() {
-    local pkg=""
+    local progname=${0##*/}
+    case "$1" in
+        -h | --help) echo2 "Usage: $progname [-h | --help] pkg-name [field-name]"; return 0 ;;
+    esac
+    local pkgname="$1"
+    local fieldname="$2"      # optional, default: URL
+    [ "$fieldname" ] || fieldname=URL
     local helper=paru
-    [ -x /usr/bin/$helper ] || helper=yay
-    local field="URL"
-
-    Options "$@"
-
-    local data=$(LANG=C $helper -Si "$pkg")
-    [ -z "$data" ] && DIE "no data found for package '$pkg'"
-
-    local url=$(echo "$data" | grep "^$field" | awk '{print $NF}')
-    if [ -z "$url" ] ; then
-        case "$field" in
-            "AUR URL") field="URL" ;;
-            URL)       field="AUR URL" ;;
-        esac
-        echo "==> changed field to '$field'" >&2
-        url=$(echo "$data" | grep "^$field" | awk '{print $NF}')
-    fi
-    [ -z "$url" ] && DIE "package '$pkg' has no field '$field'"
-
-    setsid xdg-open "$url" &> /dev/null
+    [ -x /bin/$helper ] || helper=yay
+    [ -x /bin/$helper ] || helper=pacman
+    local data=$(LANG=C $helper -Sii "$pkgname" 2>/dev/null)
+    [ "$data" ] || DIE "$pkgname info not found"
+    local info=$(echo "$data" | grep -w "^$fieldname" | sed -E "s|^$fieldname[ ]+:[ ]+||")
+    [ "$info" ] || DIE "field-name '$fieldname' not found"
+    echo2 "$info"
+    case "$fieldname" in
+        URL | "AUR URL") setsid xdg-open "$info" &>/dev/null ;;
+    esac
 }
 
 Main "$@"
