.

diff --git a/PKGBUILDs/pkgurl/pkgurl b/PKGBUILDs/pkgurl/pkgurl
--- a/PKGBUILDs/pkgurl/pkgurl
+++ b/PKGBUILDs/pkgurl/pkgurl
@@ -4,24 +4,54 @@ echo2() { echo "$@" >&2; }
 DIE() {
     local progname=${0##*/}
     echo2 "$progname: error: $1"
+    Main --help
     exit 1
 }
 
 Main() {
     local progname=${0##*/}
-    case "$1" in
-        -h | --help) echo2 "Usage: $progname [-h | --help] pkg-name [field-name]"; return 0 ;;
-    esac
-    local pkgname="$1"
-    local fieldname="$2"      # optional, default: URL
+    local pkg_name=""
+    local fieldname="URL"      # optional, default: URL
+
+    while [ "$1" ] ; do
+        case "$1" in
+            -p=* | --pkg=*)   pkg_name=${1#*=} ;;
+            -f=* | --field=*) fieldname=${1#*=} ;;
+            -h | --help)
+                cat <<EOF >&2
+Usage:   $progname [options]
+Options:
+    -h,   --help        This help.
+    -p=*, --pkg=*       Name of the package.
+    -f=*, --field=*     Name of the field in 'yay -Sii pkg_name'. Default: URL
+
+If no options and if a PKGBUILD file exists in the current folder, its URL is used.
+EOF
+                return 0
+                ;;
+        esac
+        shift
+    done
     [ "$fieldname" ] || fieldname=URL
+
     local helper=paru
     [ -x /bin/$helper ] || helper=yay
     [ -x /bin/$helper ] || helper=pacman
-    local data=$(LANG=C $helper -Sii "$pkgname" 2>/dev/null)
-    [ "$data" ] || DIE "$pkgname info not found"
+
+    if [ "$pkg_name" ] ; then
+        :
+    elif [ -e PKGBUILD ] ; then
+        source PKGBUILD
+        pkg_name="$pkgname"
+    else
+        DIE "no option nor PKGBUILD"
+    fi
+
+    local data=$(LANG=C $helper -Sii "$pkg_name" 2>/dev/null)
+    [ "$data" ] || DIE "$pkg_name info not found"
     local info=$(echo "$data" | grep -w "^$fieldname" | sed -E "s|^$fieldname[ ]+:[ ]+||")
     [ "$info" ] || DIE "field-name '$fieldname' not found"
+
     echo2 "$info"
     case "$fieldname" in
         URL | "AUR URL") setsid xdg-open "$info" &>/dev/null ;;
