small improvements

diff --git a/PKGBUILDs/m-common/generate-xfce4-desktop-xml b/PKGBUILDs/m-common/generate-xfce4-desktop-xml
--- a/PKGBUILDs/m-common/generate-xfce4-desktop-xml
+++ b/PKGBUILDs/m-common/generate-xfce4-desktop-xml
@@ -3,14 +3,15 @@
 DIE() { echo "$progname: error: $1" >&2; exit 1; }
 
 Start() {
-    cat <<EOF
+    cat <<EOF  >> "$outfilepath"
 <?xml version="1.1" encoding="UTF-8"?>
 
 <channel name="xfce4-desktop" version="1.0">
 EOF
 }
 End() {
-    cat <<EOF
+    if [ $minimal = no ] ; then
+        cat <<EOF >> "$outfilepath"
   <property name="last" type="empty">
     <property name="window-width" type="int" value="$win_width"/>
     <property name="window-height" type="int" value="$win_height"/>
@@ -32,6 +33,9 @@ End() {
     <property name="show-workspace-names" type="bool" value="true"/>
     <property name="show-submenus" type="bool" value="false"/>
   </property>
+EOF
+    fi
+    cat <<EOF >> "$outfilepath"
 </channel>
 EOF
 }
@@ -72,8 +76,13 @@ Monitors() {
 
             case "$XDG_SESSION_TYPE" in
                 wayland)
-                    [ -x /bin/wlr-randr ] || DIE "package wlr-randr is required but not installed"
-                    mons=$(echo $(/bin/wlr-randr | grep "^[A-Za-z]" | awk '{print $1}'))
+                    if [ -x /bin/wlr-randr ] ; then
+                        mons=$(echo $(/bin/wlr-randr | grep "^[A-Za-z]" | awk '{print $1}'))
+                    elif [ -x /bin/xrandr ] ; then
+                        mons=$(echo $(/bin/xrandr | grep "$grepstr" | awk '{print $1}'))
+                    else
+                        DIE "package wlr-randr or xorg-xrandr is required but not installed"
+                    fi
                     ;;
                 x11)
                     [ -x /bin/xrandr ] || DIE "package xorg-xrandr is required but not installed"
@@ -95,18 +104,25 @@ Monitors() {
 
 Usage() {
     cat <<EOF >&2
-Purpose: generate the contents of file xfce4-desktop.xml to standard output.
-Usage:   $progname [options]
-Options: --wall=X           X = full path to the desired wallpaper file.
+Purpose: generate the contents of file xfce4-desktop.xml.
+Usage:   $progname [options] [outfile]
+Options: --help, -h         This help.
+         --wall=X           X = full path to the desired wallpaper file.
          --width=X          X = window width property.
          --height=X         X = window height property.
          --monster, -m      Created xml file includes a large set of interface types.
          --detected, -d     (x11) Created xml file is based on connected and disconnected interface types.
          --tiny, -d         (x11) Created xml file is based on connected interface types.
          --minimal          Provide much less details in the generated entries.
+Outfile: Output file X is the full path for the generated xml file. Examples:
+           /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
+           \$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
+         If this file is not given, the output goes to standard output.
 EOF
     [ "$1" ] && exit $1
 }
+
+echox() { echo "$@" >> "$outfilepath"; }
 
 Main() {
     local -r progname=${0##*/}
@@ -115,48 +131,74 @@ Main() {
     local win_height="1011"
     local minimal=no
     local monitors=""
-
+    local outfilepath=""
+    local outfileis=""
+    local datetime=""
     local mode="monster"     # "monster" (=default) or "detected" or "tiny"
 
     for arg in "$@" ; do
         case "$arg" in
+            --wall=*)        wallpaper=${arg#*=} ;;
+            --width=*)       win_width=${arg#*=} ;;
+            --height=*)      win_height=${arg#*=} ;;
             --help     | -h) Usage 0 ;;
             --detected | -d) mode=detected ;;
             --monster  | -m) mode=monster ;;
             --tiny     | -t) mode=tiny ;;
             --minimal)       minimal=yes ;;
-            --wall=*)        wallpaper=${arg#*=} ;;
-            --width=*)       win_width=${arg#*=} ;;
-            --height=*)      win_height=${arg#*=} ;;
-            -*) DIE "unsupported option '$arg'" ;;
-            *)  DIE "unsupported parameter '$arg'" ;;
+            -*)              DIE "unsupported option '$arg'" ;;
+            *)               outfilepath="$arg"
+                             ;;
         esac
     done
-
     Monitors monitors
+
+    [ "$outfilepath" ] || {
+        outfilepath="$(mktemp)"
+        outfileis=tmp
+    }
+    outfilepath=$(realpath "$outfilepath")
+
+    case "$outfilepath" in
+        /home/*)
+            if [ -e "$outfilepath" ] ; then
+                datetime=$(date +%Y%m%d-%H%M%S)
+                echo "$progname: backup to $outfilepath.bak.$datetime" >&2
+                mv "$outfilepath" "$outfilepath.bak.$datetime"
+            fi
+            ;;
+    esac
+
+    rm -f "$outfilepath"
 
     Start
 
-    echo '  <property name="backdrop" type="empty">'
-    echo '    <property name="screen0" type="empty">'
+    echox '  <property name="backdrop" type="empty">'
+    echox '    <property name="screen0" type="empty">'
     for monitor in $monitors ; do
-        echo "      <property name=\"$monitor\" type=\"empty\">"
+        echox "      <property name=\"$monitor\" type=\"empty\">"
         for workspace in workspace{0..4} ; do
-            echo "        <property name=\"$workspace\" type=\"empty\">"
+            echox "        <property name=\"$workspace\" type=\"empty\">"
             if [ $minimal = no ] ; then
-                echo '          <property name="color-style" type="int" value="0"/>'
-                echo '          <property name="image-style" type="int" value="5"/>'
+                echox '          <property name="color-style" type="int" value="0"/>'
+                echox '          <property name="image-style" type="int" value="5"/>'
             fi
-            echo "          <property name=\"last-image\" type=\"string\" value=\"$wallpaper\"/>"
-            echo "        </property>"
+            echox "          <property name=\"last-image\" type=\"string\" value=\"$wallpaper\"/>"
+            echox "        </property>"
         done
-        echo "      </property>"
+        echox "      </property>"
     done
-    echo '    </property>'
-    echo '  </property>'
+    echox '    </property>'
+    echox '  </property>'
 
-    if [ $minimal = no ] ; then
-        End
+    End
+
+    if [ "$outfileis" = "tmp" ] ; then
+        cat "$outfilepath"
+        rm -f "$outfilepath"
+        echo "$progname: file generated to standard output" >&2
+    else
+        echo "$progname: file generated to '$outfilepath'" >&2
     fi
 }
 
