added pahis.install and fixes

diff --git a/PKGBUILDs/pahis/pahis b/PKGBUILDs/pahis/pahis
--- a/PKGBUILDs/pahis/pahis
+++ b/PKGBUILDs/pahis/pahis
@@ -3,11 +3,8 @@
 # Show info about pacman history.
 #
 
-DIE() {
-    echo "Error: $@" >&2
-    Usage
-    exit 1
-}
+DIE()    { echo "Error: $@" >&2 ; Usage ; exit 1 ; }
+ArgVal() { echo "${1#*=}" ; }
 
 Usage() {
     local progname="$(basename $0)"
@@ -15,7 +12,12 @@ Usage() {
 
 $progname: shows history information about package operations.
 
-Usage: $progname [operation] [package]
+Usage: $progname [options] [operation] [package]
+
+    options:
+                   -h
+                    --help            This help.
+                    --no-pkgchk       Do not check if the given package exists.
 
     operation      One of: $(Main --operations).
                    Tip: press the Tab key to complete the word!
@@ -35,40 +37,55 @@ EOF
 
 Main()
 {
-    local op="$1"
-    local pkg="$2"
+    local op
+    local pkg
     local output
+    local line
     local pacmanlog=/var/log/pacman.log
+    local pkgchk=1
 
-    case "$op" in
-        --operations)   # supports bash command completion
-            echo "--upgraded --downgraded --installed --removed --reinstalled"
-            return
-            ;;
-        --upgraded | --downgraded | --installed | --removed | --reinstalled)
-            op=${op:2}
-            ;;
-        "" | -h | --help)
-            Usage
-            return
-            ;;
-        -*)
-            DIE "unsupported operation '$op'"
-            ;;
-        *)
-            # $op must be a pkg or an unknown operation
-            if [ -z "$pkg" ] ; then
-                # Maybe pkg should be in $1? Then show all operations for the package.
-                pkg="$op"   # $op is not empty
-                op=""
-            else
-                DIE "unsupported operation '$op'"
-            fi
-            ;;
-    esac
+    test -z "$1" && {
+        Usage
+        return
+    }
+
+    for arg in "$@" ; do
+        case "$arg" in
+            --all-options)   # supports bash command completion
+                line="--upgraded --downgraded --installed --removed --reinstalled"
+                line+=" --no-pkgchk -h --help --operations --all-options"
+                echo "$line"
+                return
+                ;;
+            --operations)
+                echo "--upgraded --downgraded --installed --removed --reinstalled"
+                return
+                ;;
+            -h | --help)
+                Usage
+                return
+                ;;
+
+            --upgraded | --downgraded | --installed | --removed | --reinstalled)
+                op="${arg:2}"   # not checking if operation is already given
+                ;;
+            --no-pkgchk)  # useful for packages that existed but no more!
+                pkgchk=0
+                ;;
+            -*)
+                DIE "unsupported parameter '$op'"
+                ;;
+            *)
+                # a pkg name; not checking if pkg is already given
+                pkg="$arg"
+                ;;
+        esac
+    done
 
     test -n "$pkg" && {
-        pacman -Si "$pkg" >& /dev/null || DIE "package '$pkg' does not exist."
+        if [ $pkgchk -eq 1 ] ; then
+            pacman -Si "$pkg" >& /dev/null || DIE "package '$pkg' does not exist."
+        fi
     }
 
     if [ -z "$pkg" ] ; then
