.

diff --git a/PKGBUILDs/arch-rankmirrors/arch-rankmirrors b/PKGBUILDs/arch-rankmirrors/arch-rankmirrors
--- a/PKGBUILDs/arch-rankmirrors/arch-rankmirrors
+++ b/PKGBUILDs/arch-rankmirrors/arch-rankmirrors
@@ -14,7 +14,6 @@ DIE() {
 Indent() { sed 's|^|    |' ; }
 
 Rank() {
-
     Verbose2 "Ranking, please wait ..."
 
     local url="https://archlinux.org/mirrorlist/?use_mirror_status=on"
@@ -73,19 +72,72 @@ Rank() {
     SaveToFile
 }
 
+UserPreferredMirrors() {
+    if [ ${#USER_PREFERRED_MIRRORS[@]} -gt 0 ] ; then
+        printf "# User preferred -->\n"                       >> "$file"
+        printf "Server = %s\n" "${USER_PREFERRED_MIRRORS[@]}" >> "$file"
+        printf "# User preferred <--\n\n"                     >> "$file"
+    fi
+}
+
+LineOfRepeatedChars() {
+    local -n targetline="$1"
+    local repeat_char="$2"
+    local len="$3"
+    builtin printf -v targetline "%.s$repeat_char" $(seq 1 $len)
+}
+
+HeadingAndDataToFile() {
+    local file="$1"
+    local date="$(date -u "+%Y-%m-%d %H:%M") UTC"
+    local line="### Arch Linux mirrorlist generated by $progname ###"
+    local edgeline=""
+
+    LineOfRepeatedChars edgeline "#" "${#line}"
+
+    # heading
+    cat <<EOF > "$file"
+$edgeline
+$line
+$edgeline
+# With: $cmdline
+# When: $date
+$edgeline
+
+EOF
+    # mirrors preferred by the user
+    UserPreferredMirrors
+
+    # data (mirrorlist)
+    echo "$mirrorlist" >> "$file"
+
+    # background info in verbose mode
+    if [ "$verbose" = "yes" ] ; then
+        printf "\n### Ranking data:\n"                 >> "$file"
+        echo "$ranked" | sed 's|^|# |' | column -t >&2 >> "$file"
+
+        if [ $(stat -c %s "$rank_fails_file") -gt 0 ] ; then
+            printf "\n### Ranking problems:\n"   >> "$file"
+            cat $rank_fails_file | sed 's|^|# |' >> "$file"
+        fi
+    fi
+}
+
 SaveToFile() {
     if [ -n "$savefile" ] ; then
-        local mirrorlist=$(echo "$ranked" | grep -Pv '^URL|^~~~' | awk '{print $1}' | sed 's|^|Server = |')
+        local mirrorlist=$(echo "$ranked" | grep -Pv '^~~~|^Mirror' | awk '{print $1}' | sed 's|^|Server = |')
+
+        printf2 "==> Writing $savefile ... "
 
         if touch "$savefile" 2>/dev/null ; then
-            echo "$mirrorlist" > "$savefile"
+            HeadingAndDataToFile "$savefile"
         else
-            echo2 "==> Writing $savefile:"
             local tmpfile=$(mktemp)
-            echo "$mirrorlist" > "$tmpfile"
+            HeadingAndDataToFile "$tmpfile"
             su-c_wrapper bash -c "cp '$tmpfile' '$savefile' && chmod 0644 '$savefile'"
             rm -f "$tmpfile"
         fi
+        echo2 "done."
     fi
 }
 
@@ -117,7 +169,8 @@ Lastsync_lastupdate() {
     fi
     if [ "$lastupdate" = "$lastsync" ] ; then
         mirror="${url/lastupdate}"'$repo/os/$arch'
-        printf2 "==> Warning: %s skipped because 'lastupdate' and 'lastsync' values are equal (%s)\n" "$mirror" "$lastupdate"
+        printf2 "==> Warning: %s skipped due to 'lastupdate' = 'lastsync' (%s)\n" "$mirror" "$lastupdate"
+        printf "%-64s %s\n" "$mirror" "lastsync = lastupdate" >> $rank_fails_file
         return 1
     fi
 }
@@ -237,8 +290,9 @@ Usage: $progname [options] [countries]
 Options:
   -c, --country             Rank mirrors from a list of country specs.
                             List items can be separated by commas.
-                            A country spec is either 2 letters (country code) or the name of a country.
-                            See also the output of command:
+                            A country spec is either 2 letters (country code) or
+                            the name of a country.
+                            See also the output of command
                                reflector --list-countries
                             Note that a country name including spaces must be quoted.
   -p, --protocol            Supported protocols (https, http). Default: "${def_protocols[@]}"
@@ -249,18 +303,37 @@ Options:
   -6, --ipv6                Use IPv6 addresses.
   -v, --verbose             Show more details about the operation.
       --epoch               Show the time of last update as seconds since the beginning of year 1970.
-      --issue-detect        Detect issues with all mirrors instead of only mirrors known to have problems.
+      --issue-detect        Detect issues of any mirror instead of only mirrors with known problems.
   -h, --help                This help.
 
 Country list can be given also without option -c.
 
-Note: ranking mirrors of many countries will take lots of time.
+Note: ranking mirrors from many countries will take lots of time.
+
+A configuration file at $conf2 supports the following
+settings (i.e. bash variables):
+
+  USER_PREFERRED_MIRRORS    An array of mirrors which will be at the top of the ranking results.
+                            If not set or empty, ranking continues without such preference.
+
+Example:
+       #!/bin/bash
+
+       USER_PREFERRED_MIRRORS=(
+          'https://ftp.acc.umu.se/mirror/archlinux/$repo/os/$arch'
+          'https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch'
+       )
+
 EOF
 #      --issue-skip          Skip a problematic mirror from ranking results.
 }
 
 Main() {
     local progname="$(/usr/bin/basename "$0")"
+    local cmdline="$progname $*"
+    local conf="$HOME/.config/$progname.conf"
+    local conf2='$HOME/.config/$progname.conf'
+    local USER_PREFERRED_MIRRORS=()
     local verbose=no
     local time_as_datetime=yes
     local detect_all_issues=no
@@ -288,9 +361,20 @@ Main() {
         DIE "neither 'curl' nor 'wget' was found!"
     fi
 
+    if [ -r "$conf" ] ; then
+        echo2 "Reading $conf ..."
+        source "$conf"
+    else
+        echo2 "$conf not available, using defaults."
+    fi
+
     Options "$@"
 
+    local rank_fails_file=$(mktemp)
+
     Rank "$@"
+
+    rm -f $rank_fails_file
 }
 
 Main "$@"
