.

diff --git a/PKGBUILDs/arch-rankmirrors/eos-mr b/PKGBUILDs/arch-rankmirrors/eos-mr
--- a/PKGBUILDs/arch-rankmirrors/eos-mr
+++ b/PKGBUILDs/arch-rankmirrors/eos-mr
@@ -6,10 +6,84 @@ WARN()        { echo2 -e "==> $progname: warning: $1"; }
 
 GetCurrentCountry() { cc="$(show-location-info country)"; [ "$cc" ] ; }
 
-TraverseMirrors() {
+GetContinentOfCountry() {
+    local countrycode="${1^^}"   # uppercase
+    GetContinents
+    echo "$countries_continents" | grep -w "$countrycode" | awk '{print $2}'
+}
+GetContinents() {
+    [ "$countries_continents" ] || countries_continents=$(location list-countries --show-continent)
+}
+ShowContinentCountries() {
+    local continent="$1"
+    local show="$2"       # name or code
+    if [ -x /bin/location ] ; then
+        [ "$cc" ] || GetCurrentCountry
+        GetContinents
+        local cont_country_codes=$(echo "$countries_continents" | grep "$continent" | awk '{print $1}')
+        local code
+        GetCountries
+        case "$show" in
+            code)
+                # echo "$cont_country_codes"
+                for code in $cont_country_codes ; do
+                    echo "$reflector_list_countries" | grep "$code" | awk '{print $(NF-1)}'
+                done
+                ;;
+            name)
+                local name
+                for code in $cont_country_codes ; do
+                    name=$(echo "$reflector_list_countries" | grep "$code" | sed -E 's|([A-Z].+[a-z]) .*|"\1"|')
+                    [ "$name" ] && echo "$name"
+                done
+                ;;
+        esac
+        return 0
+    else
+        WARN "package 'python-location' is required for this operation"
+        return 1
+    fi
+}
+ListCountryCodes() {
+    GetCountries
+    echo "$reflector_list_countries" | awk '{print $(NF-1)}'
+    exit 0
+}
+ListCountryNames() {
+    GetCountries
+    echo "$reflector_list_countries" | sed -E 's|([A-Z].+[a-z]) .*|"\1"|'
+    exit 0
+}
+GetCountries() {
+    local timeinfo="$HOME/.cache/$progname/timeinfo.txt"
+    local now=$(date +%j)
+    
+    if [ -z "$reflector_list_countries" ] || [ "$(< "$timeinfo")" != "$now" ] ; then
+        reflector_list_countries=$(reflector --list-countries) || DIE "cannot get list of countries"
+        reflector_list_countries=$(echo "$reflector_list_countries" | tail -n +3)
+    fi
+}
+
+TraverseMirrors-parallel() {
+    echo2 "==> $progname: ranking mirrors in parallel"
     local timeout_rank=10
     local mirrors_with_statefiles=$(echo "$mirrors" | sed "s|/\$repo/os/\$arch|/$syncfile|")
     echo "$mirrors_with_statefiles" | parallel "eos-mr-rank-mirror {} $timeout_rank $distro $time_as_datetime"
+}
+
+TraverseMirrors-sequential() {
+    echo2 "==> $progname: ranking mirrors in sequence"
+    local timeout_rank=10
+    local mirror
+    local ix=1
+    local count=$(echo "$mirrors" | wc -l)
+
+    for mirror in $mirrors ; do
+        mirror="${mirror%%/\$repo/os/\$arch}/$syncfile"
+        printf "\r==> ranking %s/$count" $((ix++)) >&2
+        eos-mr-rank-mirror "$mirror" $timeout_rank $distro $time_as_datetime
+    done
+    echo2 ""
 }
 
 DumpOptions() {
@@ -26,26 +100,6 @@ DumpOptions() {
     [ "$lopts$sopts" ] && echo $lopts $sopts
 }
 
-GetCountries() {
-    local timeinfo="$HOME/.cache/$progname/timeinfo.txt"
-    local now=$(date +%j)
-    
-    if [ -z "$reflector_list_countries" ] || [ "$(< "$timeinfo")" != "$now" ] ; then
-        reflector_list_countries=$(reflector --list-countries) || DIE "cannot get list of countries"
-        reflector_list_countries=$(echo "$reflector_list_countries" | tail -n +3)
-    fi
-}
-ListCountryCodes() {
-    GetCountries
-    echo "$reflector_list_countries" | awk '{print $(NF-1)}'
-    exit 0
-}
-ListCountryNames() {
-    GetCountries
-    echo "$reflector_list_countries" | sed -E 's|([A-Z].+[a-z]) .*|"\1"|'
-    exit 0
-}
-
 Usage() {
     cat <<EOF
 Rank Arch mirrors.
@@ -59,6 +113,7 @@ Options:
     --country-current          Add current country code for mirrors to rank.
     --list-country-codes       Show available country codes. See also: 'reflector --list-countries'.
     --ranking-data             Show ranking data too.
+    --show-continent-countries Show the country codes of a continent based on given country code.
 
 URLs:                          URL(s) of mirrors to rank.
 EOF
@@ -67,6 +122,8 @@ EOF
 Options() {
     local opts
     local lopts="country:,country-current,distro:,dump-options,help,list-country-codes,list-country-names,ranking-data"
+    lopts+=",show-continent-countrycodes:,show-continent-countrynames:"
+    lopts+=",show-current-continent-countrycodes,show-current-continent-countrynames,current-continent"
     local sopts="c:d:hlr"
 
     opts="$(/usr/bin/getopt -o=$sopts --longoptions $lopts --name "$progname" -- "$@")" || DIE "getopt error"
@@ -78,11 +135,24 @@ Options() {
             -h | --help)            Usage; exit 0 ;;
             -c | --country)         tmp="${2^^}"; countries+=( ${tmp//,/ } ); shift ;;   # must be country codes!
             -l | --country-current) GetCurrentCountry && countries+=($cc) ;;
+            --current-continent)    # rank all countries in the current continent
+                Options -c $(echo $(Options --show-current-continent-countrycodes) | tr ' ' ',')
+                ;;
             -d | --distro)          distro="$2"; shift ;;
             -r | --ranking-data)    ranking_data=yes ;;
             --dump-options)         DumpOptions; exit 0 ;;
             --list-country-codes)   ListCountryCodes; exit 0 ;;
             --list-country-names)   ListCountryNames; exit 0 ;;
+            --show-continent-countrycodes) ShowContinentCountries "$2" code; exit ;;
+            --show-continent-countrynames) ShowContinentCountries "$2" name; exit ;;
+            --show-current-continent-countrycodes)
+                GetCurrentCountry && ShowContinentCountries "$(GetContinentOfCountry $cc)" code
+                exit
+                ;;
+            --show-current-continent-countrynames)
+                GetCurrentCountry && ShowContinentCountries "$(GetContinentOfCountry $cc)" name
+                exit
+                ;;
         esac
         shift
     done
@@ -100,12 +170,14 @@ Main() {
     local time_as_datetime=no
     local ranking_data=no
     local countries=()          # contains only uppercase country codes
-    local cc                    # current country
+    local cc=""                 # current country
+    local countries_continents=""
     local tmp
     local suffix=""
     local reflector_list_countries=""
+    local has_parallel=yes
 
-    [ -x /bin/parallel ] || DIE "package 'parallel' is required"
+    [ -x /bin/parallel ] || has_parallel=no # DIE "package 'parallel' is required"
 
     Options "$@"
 
@@ -114,7 +186,7 @@ Main() {
             distro=arch
             if [ ${#countries[@]} -eq 0 ] ; then
                 echo2 "==> option --country not used -> automatically adding the current country for ranking, if possible"
-                GetCurrentCountry && countries+=($cc) && echo2 "==> added: FI" || DIE "no countries given for ranking."
+                GetCurrentCountry && countries+=($cc) && echo2 "==> added: $cc" || DIE "no countries given for ranking."
             fi
             mirrorlist=/etc/pacman.d/mirrorlist
             syncfile=lastupdate
@@ -137,7 +209,10 @@ Main() {
         *)  DIE "distro $distro not supported." ;;
     esac
 
-    result=$(TraverseMirrors)
+    case "$has_parallel" in
+        yes) result=$(TraverseMirrors-parallel) ;;
+        no)  result=$(TraverseMirrors-sequential) ;;
+    esac
 
     local ranked=$(echo "$result" | column -t -s'|' | LC_ALL=C sort -k2rb,2 -k3b,3)   # sort: age
 
diff --git a/PKGBUILDs/arch-rankmirrors/eos-mr-rank-mirror b/PKGBUILDs/arch-rankmirrors/eos-mr-rank-mirror
--- a/PKGBUILDs/arch-rankmirrors/eos-mr-rank-mirror
+++ b/PKGBUILDs/arch-rankmirrors/eos-mr-rank-mirror
@@ -1,10 +1,15 @@
 #!/bin/bash
 
-GetFile() {
+echo2()       { echo "$@" >&2; }
+DIE()         { echo2 -e "==> $progname: error:\n    $1"; exit 1; }
+WARN()        { echo2 -e "==> $progname: warning: $1"; }
+
+RankMirror() {
     local url="$1"
     local timeout_rank="$2"
     local distro="$3"
     local time_as_datetime="$4"
+    local -r progname=${0##*/}
 
     [ "$url" ] || DIE "no URL to test"
 
@@ -34,9 +39,9 @@ GetFile() {
             echo "${url%/*}|$syncnr|$time"
             ;;
         *)
-            WARN "$url failed, code $curl_exitcode"
+            WARN "$url fetching failed\n      -> (curl: $(curl-exit-code-to-string $curl_exitcode))"
             ;;
     esac
 }
 
-GetFile "$@"
+RankMirror "$@"
