.

diff --git a/PKGBUILDs/cd-extended/ncd b/PKGBUILDs/cd-extended/ncd
--- a/PKGBUILDs/cd-extended/ncd
+++ b/PKGBUILDs/cd-extended/ncd
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Enhance CDPATH so that
+# Enhance CDPATH and cd:
 #   - if multiple matches, make round robin with them
 
 DIE() {
@@ -9,32 +9,24 @@ DIE() {
 }
 
 ncd() {
-    local dir matches=() ix count found=no
+    local newdir="$1"
+    local dir matches=() ix count
 
-    for dir in "${CDPATH_ARR[@]}" ; do
-        if [ -d "$dir/$newdir" ] ; then
-            matches+=("$dir/$newdir")
-        fi
+    for dir in ${CDPATH//:/ } ; do
+        [ -d "$dir/$newdir" ] && matches+=("$dir/$newdir")
     done
     count=${#matches[@]}
     case "$count" in
-        0) dir="$newdir" ;;         # no match in CDPATH_ARR
-        1) dir="${matches[0]}" ;;   # one match in CDPATH_ARR
+        0) dir="$newdir" ;;         # no match in CDPATH
+        1) dir="${matches[0]}" ;;   # one match in CDPATH
         *)
-            # many matches in CDPATH_ARR
-            for ((ix=0; ix < ${#matches[@]}; ix++)) ; do
-                if [ "${matches[$ix]}" -ef "$PWD" ] ; then
-                    found=yes
-                    break
-                fi
+            # many matches in CDPATH
+            for ((ix=0; ix < count; ix++)) ; do
+                [ "${matches[$ix]}" -ef "$PWD" ] && break
             done
-            if [ "$found" = "no" ] ; then
-                ix=0
-            else
-                ((ix++)) ; [ $ix -ge $count ] && ix=0
-            fi
-            dir="${matches[$ix]}"
+            [ $ix -ge $((count-1)) ] && ix=0 || ((ix++))
             echo "($((ix+1))/$count)" >&2
+            dir="${matches[$ix]}"
             ;;
     esac
 
@@ -43,15 +35,12 @@ ncd() {
 
 Main()
 {
-    local newdir="$1"
-    local bcd="builtin cd"
-
-    source ~/.config/cd-extended.conf || DIE ""
-
-    case "$newdir" in
-        "") echo "$newdir" ;;
-        .* | /* | -) echo "$newdir" ;;
-        *) ncd "$newdir" ;;
+    case "$1" in
+        "")          ;;
+        .* | /* | -) echo "$@" ;;
+        -[LP@])      echo "$@" ;;   # ncd does not support options currently
+        -*)          echo "$@" ;;   # error
+        *)           ncd  "$@" ;;
     esac
 }
 
