.

diff --git a/PKGBUILDs/GitUpdate/UpdateSources b/PKGBUILDs/GitUpdate/UpdateSources
--- a/PKGBUILDs/GitUpdate/UpdateSources
+++ b/PKGBUILDs/GitUpdate/UpdateSources
@@ -7,54 +7,37 @@ DIE() {
     exit 1
 }
 
-Pushd() { pushd "$@" >/dev/null || DIE "'pushd $*' failed." ; }
-Popd()  { popd  "$@" >/dev/null || DIE "'popd $*' failed." ; }
-
-_git_check__not_used() {
-    local folder="$1"
-
-    if [ -n "$(/usr/bin/git fetch --dry-run 2>&1)" ] ; then
-        read -p "    $folder: 'git pull' now (Y/n)? " >&2
-        case "$REPLY" in
-            ""|[yY]*) which logstuff >& /dev/null && logstuff on ; /usr/bin/git pull ;;
-        esac
-    else
-        echo "    up to date: $folder"
-    fi
-}
+pushd() { /bin/pushd "$@" >/dev/null || DIE "'pushd $*' failed." ; }
+popd()  { /bin/popd  "$@" >/dev/null || DIE "'popd $*' failed." ; }
 
 _git_check() {
+    local ret=0
     printf "====> %-30s: " "$folder"
-    if [ $need_logstuff = yes ] ; then
-        which logstuff >& /dev/null && logstuff on
-    fi
-    git pull
+    pushd "$PWD/$folder"               # using $PWD because $CDPATH may confuse 'cd' !
+    git pull || ret=$?
+    popd
+    return $ret
 }
 
 Main()
 {
     local progname="$(basename "$0")"
     local folder
-    local need_logstuff=no
 
     for folder in $(/usr/bin/ls -1) ; do
+        [ -e $folder/.skip-auto-update ] && continue
         [ -d $folder/.git ] || continue
         [ -L $folder/.git ] && continue
-        [ -e $folder/.skip-auto-update ] && continue
 
         if [ -e $folder/.ask-auto-update ] ; then
             read -p "want to check folder '$folder' (y/N)? " >&2
             case "$REPLY" in
-                [yY]*) need_logstuff=yes ;;
+                [yY]*) which logstuff >& /dev/null && logstuff on ;;
                 *) continue ;;
             esac
         fi
 
-        Pushd "$PWD/$folder"   # (warning: $CDPATH may mix up!?)
-
         _git_check
-
-        Popd
     done
 }
 
