support for using subdirs

diff --git a/PKGBUILDs/fetch-iso/fetch-iso b/PKGBUILDs/fetch-iso/fetch-iso
--- a/PKGBUILDs/fetch-iso/fetch-iso
+++ b/PKGBUILDs/fetch-iso/fetch-iso
@@ -30,19 +30,27 @@ ShowFiles() {
 
 FetchIsoFile() {
     # Fetch the given ISO file.
+    local file="$1"
+    local subdir="$2"
+    local url
+
+    case "$subdir" in
+        "") url="$URLBASE/$file" ;;
+        *)  url="$URLBASE/$subdir/$file" ;;
+    esac
+
     echo2 "==> Downloading..."
     local targetopt=""
-    local file="$1"
     case "$getter" in
         curl)
             [ "$TARGETDIR" ] && targetopt="-o$TARGETDIR/$file"
-            /bin/curl --fail -m 300 --remote-name-all "$targetopt" -u "$HELLO" "$URLBASE/$file" || exitcode=$?
-            [ $exitcode = 0 ] || DIE "downloading $URLBASE/$file failed, exit code $exitcode from 'curl'" "$exitcode"
+            /bin/curl --fail -m 300 --remote-name-all "$targetopt" -u "$HELLO" "$url" || exitcode=$?
+            [ $exitcode = 0 ] || DIE "downloading $url failed, exit code $exitcode from 'curl'" "$exitcode"
             ;;
         wget)
             [ "$TARGETDIR" ] && targetopt="-O$TARGETDIR/$file"
-            /bin/wget -q "$targetopt" --show-progress --user "$ACCOUNT" --password "$PASSWORD" "$URLBASE/$file" || exitcode=$?
-            [ $exitcode = 0 ] || DIE "downloading $URLBASE/$file failed, exit code $exitcode from 'wget'" "$exitcode"
+            /bin/wget -q "$targetopt" --show-progress --user "$ACCOUNT" --password "$PASSWORD" "$url" || exitcode=$?
+            [ $exitcode = 0 ] || DIE "downloading $url failed, exit code $exitcode from 'wget'" "$exitcode"
             ;;
     esac
 }
@@ -160,21 +168,34 @@ Main() {
             fzf --exact +i --tac
             --header="Navigation: Up, Down, PgUp, PgDn; ENTER=accept, ESC=quit"
         )
-        if true ; then
-            local selected=$(${progname}-show-all-info | "${fzf[@]}" )
-            selected=${selected%% *}
-        else
-            local selected=$(ShowFiles -q | "${fzf[@]}" )
-        fi
-        if [ "$selected" ] ; then
-            read -p "Download $selected now (Y/n)? "
-            case "$REPLY" in
-                "" | [Yy]*) FetchIsoFile $selected ;;
-                *) return 1 ;;
+        local selected=""
+        local subdir=""
+        while true ; do
+            selected=$(${progname}-show-all-info "$subdir" | "${fzf[@]}" )
+            selected=${selected%% *}                                 # keep the file name, drop other info
+
+            case "$selected" in
+                *"/") case "$selected" in
+                          "/") subdir=""
+                               ;;
+                          *)   case "$subdir" in
+                                   "") subdir="${selected%/}" ;;
+                                   *)  subdir="$subdir/${selected%/}" ;;
+                               esac
+                               ;;
+                      esac
+                      ;;
+                "")   echo2 "Nothing selected."
+                      exit 1
+                      ;;
+                *)    read -p "Download $selected now (Y/n)? "
+                      case "$REPLY" in
+                          "" | [Yy]*) FetchIsoFile "$selected" "$subdir"; exit 0 ;;
+                          *)          exit 1 ;;
+                      esac
+                      ;;
             esac
-        else
-            DIE "nothing selected"
-        fi
+        done
     fi
 
     # Exit code:
diff --git a/PKGBUILDs/fetch-iso/fetch-iso-show-all-info b/PKGBUILDs/fetch-iso/fetch-iso-show-all-info
--- a/PKGBUILDs/fetch-iso/fetch-iso-show-all-info
+++ b/PKGBUILDs/fetch-iso/fetch-iso-show-all-info
@@ -6,6 +6,8 @@ DIE() {
 }
 
 Main() {
+    local subdir="$1"
+    local dir=""
     local data
     local files=()
     local dates=()
@@ -27,17 +29,36 @@ Main() {
         fi
     fi
 
-    case "$APP" in
-        curl) data=$(/bin/curl --fail -Lsm 30 -o- -u "$HELLO" "$URLBASE")                      || DIE "failed fetching the info page '$URLBASE'." ;;
-        wget) data=$(/bin/wget -qO - --user "${HELLO%:*}" --password "${HELLO#*:}" "$URLBASE") || DIE "failed fetching the info page '$URLBASE'." ;;
+    case "$subdir" in
+        "") dir="$URLBASE" ;;
+        *)  dir="$URLBASE/$subdir" ;;
     esac
-    data=$(echo "$data" | grep '"indexcolsize">[0-9]')
-    count=$(echo "$data" | wc -l)
 
-    readarray -t files <<< $(echo "$data" | sed -E 's|.*"indexcolname"><a href="([^"]+)".*|\1|g')
-    readarray -t dates <<< $(echo "$data" | sed -E 's|.*"indexcollastmod">([0-9-]+ [0-9:]+)[ ]*<.*|\1|g')
-    readarray -t sizes <<< $(echo "$data" | sed -E 's|.*"indexcolsize">([0-9\.A-Z]+)[ ]*<.*|\1|g')
+    case "$APP" in
+        curl) data=$(/bin/curl --fail -Lsm 30 -o- -u "$HELLO" "$dir")                      || DIE "failed fetching the info page '$dir'." ;;
+        wget) data=$(/bin/wget -qO - --user "${HELLO%:*}" --password "${HELLO#*:}" "$dir") || DIE "failed fetching the info page '$dir'." ;;
+    esac
+    # data=$(echo "$data" | grep -P 'alt="\[   \]"|alt="\[DIR\]"|alt="\[PARENTDIR\]"')
+    data=$(echo "$data" | grep -P 'alt="\[   \]"|alt="\[DIR\]"')
 
+    if true ; then                            # TODO: add directory support into fetch-iso too!
+        # directories
+        local dirs=() tmp=()
+        # readarray -t tmp <<< $(echo "$data" | grep -P 'alt="\[DIR\]"|alt="\[PARENTDIR\]"' | sed -E 's|.*"indexcolname"><a href="([^"]+)".*|\1|g')
+        readarray -t tmp <<< $(echo "$data" | grep 'alt="\[DIR\]"' | sed -E 's|.*"indexcolname"><a href="([^"]+)".*|\1|g')
+        dirs+=("/ (site's root dir)")
+        [ "$tmp" ] && dirs+=("${tmp[@]}")
+        count=${#dirs[@]}
+        for ((ix=0; ix<count; ix++)) ; do
+            echo "${dirs[$ix]}" # >&2           # TODO: out to stdin
+        done
+    fi
+
+    # files
+    readarray -t files <<< $(echo "$data" | grep 'alt="\[   \]"' | sed -E 's|.*"indexcolname"><a href="([^"]+)".*|\1|g')
+    readarray -t dates <<< $(echo "$data" | grep 'alt="\[   \]"' | sed -E 's|.*"indexcollastmod">([0-9-]+ [0-9:]+)[ ]*<.*|\1|g')
+    readarray -t sizes <<< $(echo "$data" | grep 'alt="\[   \]"' | sed -E 's|.*"indexcolsize">([0-9\.A-Z]+)[ ]*<.*|\1|g')
+    count=${#files[@]}
     for ((ix=0; ix<count; ix++)) ; do
         echo "${files[$ix]}|${dates[$ix]}|${sizes[$ix]}"
     done | column -t -s"|" | sort -k2 -k3
