.

diff --git a/PKGBUILDs/usb-device-drivers/usb-device-drivers b/PKGBUILDs/usb-device-drivers/usb-device-drivers
--- a/PKGBUILDs/usb-device-drivers/usb-device-drivers
+++ b/PKGBUILDs/usb-device-drivers/usb-device-drivers
@@ -1,87 +1,124 @@
 #!/bin/bash
 
 # Detect drivers for USB devices, and possibly install them.
+# Note: USB devices must be plugged in and powered on!
 #
 # Currently only one Brother printer is in the database.
 
+echo2() { echo "$@" >&2 ; }
 DIE() {
-    echo "$progname: error: $1" >&2
+    echo2 "$progname: error: $1"
     exit 1
 }
 
 Install() {
+    local device="${detected_devices[$1]}"
+    shift
     local driver
     local repo
     local prompt
-    local helper=/usr/bin/paru
-    [ -x $helper ] || helper=/usr/bin/yay
-    [ -x $helper ] || DIE "no AUR helper installed" >&2
+    local helper=yay
     local info
     local to_install=()
     local Device="Device: "
     local indent="        "  # use the length of $Device !
 
+    which $helper >& /dev/null || helper=paru
+    which $helper >& /dev/null || DIE "no AUR helper installed"
+
     printf "%s%s\n" "$Device" "$device" >&2
 
     for driver in "$@" ; do
-        info="$($helper -Si "$driver")"
+        info="$(LANG=C $helper -Si "$driver")"
         if [ -n "$info" ] ; then
-            if ( $(pacman -Q "$driver" >& /dev/null) ) ; then
-                echo "${indent}driver: $driver [installed]" >&2
+            if [ 1 -eq 1 ] && ( $(pacman -Q "$driver" >& /dev/null) ) ; then
+                echo2 "${indent}driver: $driver [installed]"
             else
                 repo="$(echo "$info" | grep ^Repository | awk '{print $NF}')"
-                case "$repo" in
-                    aur) prompt="${indent}Install driver $driver from AUR (Y/n)? " ;;
-                    *)   prompt="${indent}Install driver $driver (Y/n)? " ;;
-                esac
-                read -p "$prompt" >&2
-                case "$REPLY" in
-                    ""|[yY]*) to_install+=("$driver") ;;
-                esac
+                driver="$repo/$driver"
+                to_install+=("$driver")
             fi
         else
-            echo "${indent}driver: [unknown]" >&2
+            echo2 "${indent}driver: [unknown]"
         fi
     done
-    [ -n "$to_install" ] && $helper -S "${to_install[@]}"
+    [ -n "$to_install" ] && echo "===> $helper -S ${to_install[@]}"
+}
+
+DetectedDevices() {
+    local usb_devices
+    local line
+    local id name
+    local xx
+
+    readarray -t usb_devices <<< $(lsusb)
+
+    for line in "${usb_devices[@]}" ; do
+        id=$(echo "$line" | cut -d' ' -f6)
+        name=$(echo "$line" | cut -d' ' -f7-)
+
+        # same device may be on different bus numbers...
+        for xx in "${detected_ids[@]}" ; do
+            if [ "$xx" = "$id" ] ; then
+                break
+            fi
+        done
+        if [ "$xx" != "$id" ] ; then
+            detected_devices["$id"]="$name"
+            detected_ids+=("$id")
+        fi
+    done
+}
+
+KnownDrivers() {
+    local line id drivers
+    local databasefile=/usr/share/endeavouros/scripts/usb-device-drivers-database.txt
+    [ -r "$databasefile" ] || databasefile=./usb-device-drivers-database.txt
+    [ -r "$databasefile" ] || DIE "$databasefile is missing"
+
+    readarray -t usb_device_database <<< $(cat "$databasefile" | grep -Pv '^[ \t]*#.*$|^[ \t]*$')
+
+    if [ -z "$usb_device_database" ] ; then
+        DIE "Database of known drivers is empty!"
+    fi
+
+    for line in "${usb_device_database[@]}" ; do
+        id=$(echo "$line" | awk '{print $1}')
+        line=$(echo "$line" | sed "s|^[ \t]*$id[ \t]*||")  # remove id
+        line=$(echo "$line" | sed "s|[ \t]*#.*||")         # remove trailing comment
+        drivers="$line"
+        known_drivers["$id"]="$drivers"
+        known_ids+=("$id")
+    done
 }
 
 Main()
 {
     local progname=$(basename "$0")
-    local tokens_on_line=3
-    local databasefile=/usr/share/endeavouros/scripts/usb-device-drivers-database.bash
-    [ -r "$databasefile" ] || DIE "$databasefile is missing"
-    if [ 0 -eq 1 ] ; then
-        local usb_device_database=(
-            # Every line has $tokens_on_line (currently 3) tokens:
-            #   "vendor:devid"   "driver"   "optional-driver"
-            #
-            # Important: use empty string "" for each missing token.
-            
-            # Brother multifunction: printer and scanner drivers:
-            04f9:0422  brother-dcp-l2537dw-printer  brscan4
-        )
-    fi
-    local usb_devices
     local line ix
-    local device
+    local device devicename
     local usb_device_database=()
 
-    source "$databasefile"
+    declare -A detected_devices
+    declare -A known_drivers
+    local detected_ids=()
+    local known_ids=()
 
-    readarray -t usb_devices <<< $(lsusb)
+    KnownDrivers
+    DetectedDevices
 
-    for line in "${usb_devices[@]}" ; do
-        device="$(echo "$line" | cut -d' ' -f7-)"
-        for ((ix = 0; ix < ${#usb_device_database[@]}; ix += tokens_on_line)) ; do
-            case "$line" in
-                *" ${usb_device_database[$ix]} "*)
-                    Install "${usb_device_database[$((ix+1))]}" "${usb_device_database[$((ix+2))]}"
-                    ;;
-            esac
+    local det_id kno_id found=no
+    for kno_id in "${known_ids[@]}" ; do
+        for det_id in "${detected_ids[@]}" ; do
+            if [ "$det_id" = "$kno_id" ] ; then
+                found=yes
+                Install "$kno_id" ${known_drivers[$kno_id]}
+            fi
         done
     done
+    if [ "$found" = "no" ] ; then
+        echo2 "Sorry, no known drivers found for detected devices."
+    fi
 }
 
 Main "$@"
