.

diff --git a/PKGBUILDs/pacman-ext/paccache b/PKGBUILDs/pacman-ext/paccache
--- a/PKGBUILDs/pacman-ext/paccache
+++ b/PKGBUILDs/pacman-ext/paccache
@@ -1,8 +1,17 @@
 #!/bin/bash
 
 # paccache wrapper
-# - properly handle the default value for option -k
-# - show the actual command and parameters (if --quiet not used)
+# - properly handle the default value for option -k/--keep
+# - show the actual command and parameters unless option --show-command=no is used
+
+HandleOpt_k() {  # option -k/--keep has an optional value
+    kopt="$1"
+    local val sep=""
+    local -r kd=3
+    [ "$2" ] && val="$2" || val=$kd
+    [ "$kopt" = "--keep" ] && sep="="
+    args+=("$kopt$sep$val")
+}
 
 paccache_options_to_args() {
     local opts
@@ -10,8 +19,14 @@ paccache_options_to_args() {
     local lopts="dryrun,move:,remove,arch:,cachedir:,force,help,ignore:,keep::"
     lopts+=",min-atime:,min-mtime:,nocolor,null,quiet,uninstalled,verbose,version"
 
+    # options for the local implementation!
+    sopts+="s:"
+    lopts+=",show-command:"
+
     opts="$(getopt -o=$sopts --longoptions $lopts --name "${FUNCNAME[0]}" -- "$@")" || exit 1
     eval set -- "$opts"
+
+    local kopt    # will be assigned in HandleOpt_k
 
     while true ; do
         case "$1" in
@@ -21,7 +36,7 @@ paccache_options_to_args() {
             --arch | -a)        args+=("$1" "$2"); shift ;;
             --cachedir | -c)    args+=("$1" "$2"); shift ;;
             --ignore | -i)      args+=("$1" "$2"); shift ;;
-            --keep | -k)        [ "$2" ] && args+=("$1" "$2") || args+=("$1" 3); shift ;;
+            --keep | -k)        HandleOpt_k "$@";  shift ;;
             --min-atime)        args+=("$1" "$2"); shift ;;
             --min-mtime)        args+=("$1" "$2"); shift ;;
             --dryrun | -d)      args+=("$1") ;;
@@ -30,38 +45,58 @@ paccache_options_to_args() {
             --help | -h)        args+=("$1") ;;
             --nocolor)          args+=("$1") ;;
             --null | -z)        args+=("$1") ;;
-            --quiet | -q)       args+=("$1"); quiet=yes ;;  # used in this file too
+            --quiet | -q)       args+=("$1") ;;
             --uninstalled | -u) args+=("$1") ;;
             --verbose | -v)     args+=("$1") ;;
             --version | -V)     args+=("$1") ;;
+
+            # additional options used by this local implementation:
+            --show-command | -s) show_command="$2"; shift ;;   # $2 = "yes" or "no"
         esac
         shift
     done
-    args+=("$@")
-}
 
-ShowCommand() {                                      # show the *real* command and parameters
-    if [ $quiet = no ] ; then
-        local progname=${0}
-        local arg
-        echo -n ":: $progname " >&2
-        for arg in "$@" ; do
-            if [ "${arg/ /}" = "$arg" ] ; then
-                echo -n "$arg " >&2                  # $arg includes no spaces
-            else
-                echo -n "'$arg' " >&2                # $arg includes spaces
+    local target="$1"   # the first target package name, if given
+
+    if [ "$target" ] ; then
+        # check if the first target is actually a value for option --keep
+        local pkgs=(/var/cache/pacman/pkg/"$target"-*)
+        if [ "${pkgs: -2}" = "-*" ] ; then
+            echo "==> $progname: error: target package name '$target' not found." >&2
+            if [ "$kopt" ] && [ -z "${target//[0-9]/}" ] ; then   # is a number meant for --keep ?
+                local msg="   -> Tip: if '$target' was meant for option $kopt, use syntax:"
+                case "$kopt" in
+                    -k)     echo "$msg $kopt$target" >&2 ;;
+                    --keep) echo "$msg $kopt=$target" >&2 ;;
+                esac
             fi
-        done
-        echo "" >&2
+            exit 1
+        fi
     fi
+    args+=("$@")
+    [ $show_command = yes ] && ShowCommand "${args[@]}"
+ }
+
+ShowCommand() {
+    # show the command and its *real* parameters
+    local arg
+    local line=":: $progname "
+
+    for arg in "$@" ; do
+        if [ "${arg/ /}" = "$arg" ] ; then
+            line+="$arg "                   # $arg includes no spaces
+        else
+            line+="'$arg' "                 # $arg includes spaces
+        fi
+    done
+    echo "${line% }" >&2                    # don't show the trailing space
 }
 
 Main() {
+    local -r progname=${0}
+    local show_command=yes     # "yes" or "no", "no" should be the default for compatibility
     local args=()
-    local quiet=no
     paccache_options_to_args "$@"
-    ShowCommand "${args[@]}"
-    # /bin/paccache --verbose "${args[@]}"
     /bin/paccache "${args[@]}"
 }
 
