.

diff --git a/PKGBUILDs/pacman-ext/pacman-ext b/PKGBUILDs/pacman-ext/pacman-ext
--- a/PKGBUILDs/pacman-ext/pacman-ext
+++ b/PKGBUILDs/pacman-ext/pacman-ext
@@ -169,10 +169,40 @@ EOF
     return $?
 }
 
+CheckUpdates() {
+    checkupdatesext
+    retval=$?
+
+    case "$retval" in
+        1) DIE "checkupdates failed" ;;
+        2) retval=0 ; echo "No official updates available." ;;
+        0) retval=1 ;;
+    esac
+
+    if [ -x $aur_helper ] ; then                      # || DIE "AUR helpers 'paru' or 'yay' not found."
+        local updates=$($aur_helper -Qua)
+        if [ -n "$updates" ] ; then
+            case "$retval" in
+                0) retval=2 ;;  # only AUR updates
+                1) retval=3 ;;  # both official and AUR updates
+            esac
+        else
+            echo "No AUR updates avaiable."
+        fi
+    fi
+
+    # retval:
+    #  0 = no updates available
+    #  1 = official updates available
+    #  2 = AUR updates available
+    #  3 = official and AUR updates available
+
+    #return $retval    # has the exit code of checkupdates
+}
+
 pacman_ext() {
     if [ -z "$1" ] ; then
-        CheckUpdates
-        return $retval
+        CheckUpdates && return
     fi
     local db_opt="-Sy"                     # $db_opt used by special_update()
 
@@ -205,25 +235,6 @@ pacman_ext() {
 
     verbose2 "will check need for sudo with pacman ..."
     /usr/bin/pacman-sudo-internal "$@"
-}
-
-CheckUpdates() {
-    checkupdatesext
-    retval=$?
-    case "$retval" in
-        0) ;;  # has official updates
-        1) DIE "checkupdates failed" ;;
-        2) echo "No official updates avaiable." ;;
-    esac
-
-    [ -x $aur_helper ] || DIE "AUR helpers 'paru' or 'yay' not found."
-    local updates=$($aur_helper -Qua)
-    if [ -z "$updates" ] ; then
-        echo "No AUR updates avaiable."
-    else
-        retval=0
-    fi
-    #return $retval    # has the exit code of checkupdates
 }
 
 Main() {
