.

diff --git a/PKGBUILDs/pac/pac b/PKGBUILDs/pac/pac
--- a/PKGBUILDs/pac/pac
+++ b/PKGBUILDs/pac/pac
@@ -42,11 +42,13 @@ _GitHub_is_ok() {
         has_github_mirror=yes
     else
         local list
-        for list in endeavouros-mirrorlist mirrorlist-m ; do
+        for list in $(grep "^Include = /etc/pacman.d/" /etc/pacman.conf | uniq | awk '{print $NF}') ; do
             if [ -r "/etc/pacman.d/$list" ] ; then
                 if [ -n "$(grep "^Server = " /etc/pacman.d/$list | head -n 2 | grep github)" ] ; then    # 2 is an ad hoc value...
                     has_github_mirror=yes
                 fi
+            else
+                echo "Error: file '/etc/pacman.d/$list' does not exist. Check /etc/pacman.conf." >&2
             fi
         done
     fi
