.

diff --git a/PKGBUILDs/gpg-stuff/gpg-sign-prepare b/PKGBUILDs/gpg-stuff/gpg-sign-prepare
--- a/PKGBUILDs/gpg-stuff/gpg-sign-prepare
+++ b/PKGBUILDs/gpg-stuff/gpg-sign-prepare
@@ -6,7 +6,7 @@ gpg-sign-prepare() {
 
     case "$1" in
         --bg) ;;
-        *)    $FUNCNAME --bg "$@" &
+        *)    $FUNCNAME --bg "$@"
               return
               ;;
     esac
@@ -19,11 +19,12 @@ gpg-sign-prepare() {
     while true ; do
         [ "$SIGNER" ] || SIGNER="$(gpg -K | grep -w ^uid | awk '{print $NF}' | sed 's|[<>]||g')"
         if [ $(echo "$SIGNER" | wc -l) -ne 1 ] ; then
-            echo "==> 0 or >1 signers found, using $conf instead." >&2
+            # echo "==> 0 or >1 signers found, using $conf instead." >&2
             source "$conf" || return 1
-            [ "$SIGNER" ]  || { echo "sorry, $conf failed." >&2; return 1; }
+            [ "$SIGNER" ]  || DIE "sorry, $conf failed." >&2
         fi
         tmpfile=$(mktemp)
+        gpg_code=0
         gpg --local-user "$SIGNER" \
             --output "$tmpfile.sig" --detach-sign "$tmpfile" \
             || gpg_code=$?
@@ -31,10 +32,8 @@ gpg-sign-prepare() {
         SIGNER=""
         rm -f "$tmpfile" "$tmpfile.sig"
 
-        if [ $gpg_code -ne 0 ] ; then
-            echo "$FUNCNAME: gpg failed with code $gpg_code." >&2
-            return $gpg_code
-        fi
+        [ $gpg_code -eq 0 ] || DIE "gpg failed with code $gpg_code."
+
         sleep 5m
     done
 }
