.

diff --git a/PKGBUILDs/meld-rcs/meldrcs b/PKGBUILDs/meld-rcs/meldrcs
--- a/PKGBUILDs/meld-rcs/meldrcs
+++ b/PKGBUILDs/meld-rcs/meldrcs
@@ -5,7 +5,7 @@
 # where
 #    X and Y are a normal revision numbers or a negative number: -1 = previous from HEAD, -2 = second previous, ...
 
-DIE() { echo "Error: $1" >&2 ; exit 1 ; }
+DIE() { echo "$progname: error: $1" >&2 ; exit 1 ; }
 
 RCSdir() { echo "$(dirname "$1")"/RCS ; }
 
@@ -22,6 +22,16 @@ RevFix() {
 
 MELD() {
     /bin/meld "$@"  &> /dev/null &
+}
+
+CheckRevisions() {
+    local rev
+    for rev in "$@" ; do
+        if [ -z "$(printf "%s\n" "${existing_revisions[@]}" | grep "$rev")" ] ; then
+            rm -f RCS
+            DIE "revision '$rev' does not exist"
+        fi
+    done
 }
 
 Main()
@@ -51,47 +61,54 @@ Main()
     if [ "${#args[@]}" = "1" ] ; then                    # only one file as arg?
         filepath="$(realpath "${args[0]}")"              # absolute path
         if [ -r "$filepath" ] ; then
-            if FileHasRCS "$filepath" ; then                  # is an RCS file?
-
-                # Yes, do rcsdiff stuff!
-
+            if FileHasRCS "$filepath" ; then             # is an RCS file?
                 filename="$(basename "$filepath")"
-                mkdir -p "$HOME"/.cache/$progname
-                local tmpdir="$(mktemp -d "$HOME"/.cache/$progname/$filename.XXXXX)"
-
-                rcsdir="$(RCSdir "$filepath")"
+                local tmpdir="$HOME/.cache/$progname"
+                mkdir -p "$tmpdir"                       # tmpdir for the file to be checked out for comparison
+                rcsdir="$(RCSdir "$filepath")"           # path to the RCS dir
 
                 pushd $tmpdir >/dev/null
+                ln -s $rcsdir                            # symlink to the $rcsdir
 
-                ln -s $rcsdir
+                local existing_revisions=($(rlog -b "$filepath" | grep "^revision " | awk '{print $2}'))
+
+                # Note: removing old files below *may* conflict with other $progname instances !!!
 
                 case "${#revs[@]}" in
                     0)  # FORM: meld file
-                        co "$filename" 2>/dev/null                      # RCS head
+                        rm -f "$filename".head                           # possible conflict ??
+                        co "$filename" 2>/dev/null                       # RCS head
                         mv "$filename" "$filename".head
                         MELD "$filepath" "$filename".head
                         ;;
                     1)  # FORM: meld -rX file
                         # HEAD1=$(head -n1 "$rcsdir/$filename" | awk '{print $2}' | sed 's|;$||')
                         rev1="${revs[0]}"
+                        CheckRevisions "$rev1"
+                        rm -f "$filename.$rev1"                          # possible conflict ??
                         co -r"$rev1" "$filename" 2>/dev/null
-                        mv "$filename" "$filename"."$rev1"
-                        MELD "$filepath" "$filename"."$rev1"
+                        mv "$filename" "$filename.$rev1"
+                        MELD "$filepath" "$filename.$rev1"
                         ;;
                     2)  # FORM: meld -rX -rY file
                         rev1="${revs[0]}"
                         rev2="${revs[1]}"
+                        CheckRevisions "$rev1" "$rev2"
+                        rm -f "$filename"."$rev1" "$filename"."$rev2"    # possible conflict ??
                         co -r"$rev1" "$filename" 2>/dev/null
                         mv "$filename" "$filename"."$rev1"
                         co -r"$rev2" "$filename" 2>/dev/null
                         mv "$filename" "$filename"."$rev2"
                         MELD "$filename"."$rev1" "$filename"."$rev2"
                         ;;
-                    *) DIE "there can be zero, one or two -r options" ;;
+                    *)
+                        rm -f RCS
+                        DIE "there can be zero, one or two -r options"
+                        ;;
                 esac
-
+                sleep 2                      # precaution!
+                rm -f RCS                    # remove symlink
                 popd >/dev/null
-                rm -rf $tmpdir
                 return                       # rcsdiff stuff is done now, nothing more to see here...
             fi
         fi
