.

diff --git a/PKGBUILDs/pkgcheck/pull-requests b/PKGBUILDs/pkgcheck/pull-requests
--- a/PKGBUILDs/pkgcheck/pull-requests
+++ b/PKGBUILDs/pkgcheck/pull-requests
@@ -1,82 +1,47 @@
 #!/bin/bash
-#
-# Show number of pull requests for PKGBUILDS.
-#
 
-echo2() { echo "$@" >&2 ; }
-printf2() { printf "$@" >&2 ; }
+Result() { echo -e "$1" ; }
 
-DIE() {
-    echo2 "$progname: error: $1"
-    exit 1
-}
-
-Main2()
+Main3()
 {
     local url="$1"
-    local url2="$url/issues"
-    local main_count
-    local comments
-    local strings=(
-        "Pull requests"
-        "Issues"
-    )
-    local data
-    local str
-    local maxstrlen=0
-    local maxurllen=0
-    test -n "$url" || DIE "no URL!"
+    local pagedata retval
+    local item=$(echo "$url" | sed 's|https://github\.com/||')
 
-    for str in "${strings[@]}" ; do
-        if [ $maxstrlen -lt ${#str} ] ; then
-            maxstrlen=${#str}
-        fi
+    printf "%-45s: " "$item"
+
+    pagedata=$(curl --fail -Lsm 10 -o- "$url")
+    retval=$?
+    [ $retval -ne 0 ] && DIE "curl '$url' failed"
+    local issue_numbers=$(echo "$pagedata" | grep -E '^<div id="issue_[0-9]+' | sed -E 's|^<div id="issue_([0-9]+)".*|\1|')
+    local issue_text
+    local nr
+
+    if [ -z "$issue_numbers" ] ; then
+        Result "-"
+        return
+    fi
+
+    for nr in $issue_numbers ; do
+        issue_text=$(echo "$pagedata" | sed -n "/^<div id=\"issue_$nr\"/,/^<\/div>$/p")
+        comments="$(echo "$issue_text" | grep -E 'Link--muted.*"[0-9]+ comment' | sed -E 's|.*aria-label="([0-9]+).*|\1|')"
+        case "$comments" in
+            "") Result "$last #$nr: no comments yet" ;;
+            *)  Result "$last #$nr: $comments comments" ;;
+        esac
     done
+}
 
-    for str in "${urls[@]}" ; do
-        if [ $maxurllen -lt ${#str} ] ; then
-            maxurllen=${#str}
-        fi
-    done
+Main2() {
+    local urlbase="$1"
+    local last
 
-    data="$(curl -s $url)"
-    [ -n "$data" ] || DIE "data not available!"
-
-    for str in "${strings[@]}" ; do
-
-        printf2 "%-*s for %-*s : " "$maxstrlen" "$str" "$maxurllen" "$url"
-
-        main_count="$(echo "$data" | grep -A1 "$str</span>" | tail -n 1 | sed -E 's|.*>([0-9]+)</span>$|\1|')"
-        comments=0
-
-        if true ; then
-            [ "$main_count" -gt 0 ] && echo2 "$main_count" || echo2 "-"
-        else
-            # not working...
-            case "$main_count" in
-                [1-9] | [1-9][0-9] | [1-9][0-9][0-9] | [1-9][0-9][0-9][0-9]*)
-		    comments=$(curl -s $url2 | grep -E '"[0-9]+ comment' | sed -E 's|.*/issues/([0-9]+)".* aria-label="([0-9]+) comment.*|issue \1: \2 comments|')
-                    ;;
-                *)
-                    main_count=none
-                    ;;
-            esac
-            case "$main_count" in
-	        "" | none | 0)
-                    printf2 "$main_count " ;;
-                *)
-                    printf2 "$main_count, " ;;
-            esac
-            if [ "$str" = "Issues" ] ; then
-                [ -n "$comments" ] && printf2 "%s" "$comments"
-            fi
-            printf2 "\n"
-        fi
+    for last in issues pulls ; do
+        Main3 "$urlbase/$last"
     done
 }
 
 Main() {
-    local progname="$(basename "$0")"
     local urls=(
         https://github.com/endeavouros-team/PKGBUILDS
         https://github.com/endeavouros-team/eos-bash-shared
